MAIN_PAGE_URL = "https://stellarburgers.nomoreparties.site"
LOGIN_PAGE_URL = f"{MAIN_PAGE_URL}/login"
FORGOT_PASSWORD_PAGE_URL = f"{MAIN_PAGE_URL}/forgot-password"
RESET_PASSWORD_PAGE_URL = f"{MAIN_PAGE_URL}/reset-password"
PROFILE_PAGE_URL = f"{MAIN_PAGE_URL}/account/profile"
ORDER_HISTORY_PAGE_URL = f"{MAIN_PAGE_URL}/account/order-history"
FEED_PAGE_URL = f"{MAIN_PAGE_URL}/feed"